package trivia

import "time"

// ChannelSettings controls trivia behavior for a specific channel.
type ChannelSettings struct {
	AnswerTimeSeconds int
	HintsEnabled      bool
	BasePoints        int
	MinimumPoints     int
	HintPenalty       int
	Enabled           bool
}

// StoreDefaults defines default settings used when a channel has no explicit row.
type StoreDefaults struct {
	Settings ChannelSettings
}

// StoredQuestion is a persisted trivia question.
type StoredQuestion struct {
	ID             int64
	Topic          string
	Question       string
	Answer         string
	Aliases        []string
	Hint           string
	UniquenessKey  string
	UniquenessHash string
	QuestionHash   string
	CreatedAt      time.Time
}

// GeneratedQuestion is trivia data generated by the model before persistence.
type GeneratedQuestion struct {
	Question      string   `json:"question"`
	Answer        string   `json:"answer"`
	Aliases       []string `json:"aliases"`
	Hint          string   `json:"hint"`
	UniquenessKey string   `json:"uniqueness_key"`
}

// ScoreEntry is a leaderboard row.
type ScoreEntry struct {
	Nick  string
	Score int
}
