package trivia

import (
	"strings"
	"time"
)

const (
	ModeTrivia = "trivia"
	ModeCode   = "code"

	ValidatorNormalizedExact = "normalized_exact"

	DifficultyEasy   = "easy"
	DifficultyMedium = "medium"
	DifficultyHard   = "hard"
)

var codeLanguageAliasMap = map[string]string{
	"go":         "go",
	"golang":     "go",
	"python":     "python",
	"py":         "python",
	"javascript": "javascript",
	"js":         "javascript",
	"typescript": "typescript",
	"ts":         "typescript",
	"bash":       "bash",
	"sh":         "bash",
	"shell":      "bash",
	"pascal":     "pascal",
	"c":          "c",
	"cpp":        "cpp",
	"c++":        "cpp",
	"cxx":        "cpp",
	"cc":         "cpp",
	"csharp":     "csharp",
	"c#":         "csharp",
	"cs":         "csharp",
	"java":       "java",
	"rust":       "rust",
	"php":        "php",
	"ruby":       "ruby",
	"lua":        "lua",
}

var supportedCodeLanguages = []string{
	"go",
	"python",
	"javascript",
	"typescript",
	"bash",
	"pascal",
	"c",
	"cpp",
	"csharp",
	"java",
	"rust",
	"php",
	"ruby",
	"lua",
}

// ChannelSettings controls trivia behavior for a specific channel.
type ChannelSettings struct {
	AnswerTimeSeconds     int
	CodeAnswerTimeSeconds int
	HintsEnabled          bool
	BasePoints            int
	MinimumPoints         int
	HintPenalty           int
	Enabled               bool
	Difficulty            string
	CodeDifficulty        string
}

// StoreDefaults defines default settings used when a channel has no explicit row.
type StoreDefaults struct {
	Settings ChannelSettings
}

// StoredQuestion is a persisted trivia question.
type StoredQuestion struct {
	ID             int64
	Mode           string
	Topic          string
	Language       string
	Question       string
	Answer         string
	Aliases        []string
	Hint           string
	ValidatorType  string
	UniquenessKey  string
	UniquenessHash string
	QuestionHash   string
	CreatedAt      time.Time
}

// GeneratedQuestion is trivia data generated by the model before persistence.
type GeneratedQuestion struct {
	Question      string   `json:"question"`
	Answer        string   `json:"answer"`
	Aliases       []string `json:"aliases"`
	Hint          string   `json:"hint"`
	UniquenessKey string   `json:"uniqueness_key"`
}

// GeneratedCodeQuestion is code-quiz data generated by the model before persistence.
type GeneratedCodeQuestion struct {
	Language      string   `json:"language"`
	Question      string   `json:"question"`
	Answer        string   `json:"answer"`
	Aliases       []string `json:"aliases"`
	Hint          string   `json:"hint"`
	UniquenessKey string   `json:"uniqueness_key"`
	ValidatorType string   `json:"validator_type"`
}

// ScoreEntry is a leaderboard row.
type ScoreEntry struct {
	Nick  string
	Score int
}

// GuessLog represents one channel message observed during an active round.
type GuessLog struct {
	ID        int
	Nick      string
	Message   string
	Timestamp time.Time
}

// JudgeGuessCandidate is an LLM judging input candidate.
type JudgeGuessCandidate struct {
	ID        int    `json:"id"`
	Nick      string `json:"nick"`
	Guess     string `json:"guess"`
	ElapsedMS int64  `json:"elapsed_ms"`
}

// JudgeRequest contains data for post-timeout close-answer judging.
type JudgeRequest struct {
	Mode       string
	Topic      string
	Language   string
	Question   string
	Answer     string
	Aliases    []string
	Candidates []JudgeGuessCandidate
}

// JudgeDecision is a structured LLM judging output.
type JudgeDecision struct {
	Approved   bool    `json:"approved"`
	GuessID    int     `json:"guess_id"`
	Confidence float64 `json:"confidence"`
	Reason     string  `json:"reason"`
}

// IsValidDifficulty reports whether difficulty is one of easy, medium, or hard.
func IsValidDifficulty(input string) bool {
	switch strings.ToLower(strings.TrimSpace(input)) {
	case DifficultyEasy, DifficultyMedium, DifficultyHard:
		return true
	default:
		return false
	}
}

// NormalizeDifficulty converts input to canonical difficulty, defaulting to medium.
func NormalizeDifficulty(input string) string {
	switch strings.ToLower(strings.TrimSpace(input)) {
	case DifficultyEasy:
		return DifficultyEasy
	case DifficultyHard:
		return DifficultyHard
	default:
		return DifficultyMedium
	}
}

// NormalizeMode returns a canonical game mode, defaulting to trivia.
func NormalizeMode(input string) string {
	switch strings.ToLower(strings.TrimSpace(input)) {
	case ModeCode:
		return ModeCode
	default:
		return ModeTrivia
	}
}

// NormalizeCodeLanguage maps aliases to canonical names.
func NormalizeCodeLanguage(input string) (string, bool) {
	normalized := strings.ToLower(strings.TrimSpace(input))
	language, ok := codeLanguageAliasMap[normalized]
	return language, ok
}

// SupportedCodeLanguages returns the canonical supported language list.
func SupportedCodeLanguages() []string {
	languages := make([]string, len(supportedCodeLanguages))
	copy(languages, supportedCodeLanguages)
	return languages
}
